import jsPDF from 'jspdf';
import { type PlanResults, type UserInputs } from '@/lib/calculations';

// Premium white-theme palette
const PRIMARY = [200, 40, 35] as const;      // brand red
const DARK_TEXT = [20, 20, 25] as const;      // near-black text
const BODY_TEXT = [55, 55, 65] as const;      // body copy
const LABEL = [120, 120, 130] as const;       // subtle labels
const RULE = [215, 215, 220] as const;        // light dividers
const CARD_BG = [247, 247, 250] as const;     // light card fill
const WHITE = [255, 255, 255] as const;
const ACCENT_BLUE = [45, 110, 220] as const;
const ACCENT_AMBER = [210, 155, 20] as const;

type RGB = readonly [number, number, number];

const setC = (d: jsPDF, c: RGB) => d.setTextColor(c[0], c[1], c[2]);
const setF = (d: jsPDF, c: RGB) => d.setFillColor(c[0], c[1], c[2]);
const setD = (d: jsPDF, c: RGB) => d.setDrawColor(c[0], c[1], c[2]);

function roundRect(d: jsPDF, x: number, y: number, w: number, h: number, r: number, fill: RGB) {
  setF(d, fill);
  d.roundedRect(x, y, w, h, r, r, 'F');
}

function line(d: jsPDF, x1: number, y1: number, x2: number, y2: number, c: RGB, w = 0.3) {
  setD(d, c);
  d.setLineWidth(w);
  d.line(x1, y1, x2, y2);
}

function pageFooter(d: jsPDF, pg: number, total: number) {
  const pw = d.internal.pageSize.getWidth();
  const ph = d.internal.pageSize.getHeight();
  line(d, 15, ph - 14, pw - 15, ph - 14, RULE);
  d.setFontSize(7);
  setC(d, LABEL);
  d.setFont('helvetica', 'normal');
  d.text('Generated by GearUpToFit Body Recomp OS  |  gearuptofit.com', 15, ph - 9);
  d.text(`${pg} / ${total}`, pw - 15, ph - 9, { align: 'right' });
}

function sectionTitle(d: jsPDF, y: number, title: string): number {
  const pw = d.internal.pageSize.getWidth();
  // Red accent bar
  setF(d, PRIMARY);
  d.rect(15, y, 3, 8, 'F');
  d.setFontSize(12);
  d.setFont('helvetica', 'bold');
  setC(d, DARK_TEXT);
  d.text(title.toUpperCase(), 22, y + 6);
  line(d, 15, y + 10, pw - 15, y + 10, RULE);
  return y + 16;
}

function pageBreak(d: jsPDF, y: number, need: number): number {
  const ph = d.internal.pageSize.getHeight();
  if (y + need > ph - 22) {
    d.addPage();
    // White bg
    setF(d, WHITE);
    d.rect(0, 0, d.internal.pageSize.getWidth(), ph, 'F');
    return 20;
  }
  return y;
}

function whitePage(d: jsPDF) {
  const pw = d.internal.pageSize.getWidth();
  const ph = d.internal.pageSize.getHeight();
  setF(d, WHITE);
  d.rect(0, 0, pw, ph, 'F');
}

export function generatePlanPDF(plan: PlanResults, inputs: UserInputs) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ======================== PAGE 1: COVER ========================
  whitePage(doc);

  // Top accent stripe
  setF(doc, PRIMARY);
  doc.rect(0, 0, pw, 5, 'F');

  // Brand
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setC(doc, PRIMARY);
  doc.text('GEAR UP TO FIT', pw / 2, 28, { align: 'center' });

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  setC(doc, LABEL);
  doc.text('BODY RECOMP OS', pw / 2, 33, { align: 'center' });

  // Title block
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  setC(doc, DARK_TEXT);
  doc.text('YOUR 8-WEEK', pw / 2, 60, { align: 'center' });

  doc.setFontSize(32);
  setC(doc, PRIMARY);
  doc.text(plan.goalLabel.toUpperCase(), pw / 2, 72, { align: 'center' });

  doc.setFontSize(28);
  setC(doc, DARK_TEXT);
  doc.text('PLAN', pw / 2, 84, { align: 'center' });

  // Decorative line
  setF(doc, PRIMARY);
  doc.rect(pw / 2 - 20, 90, 40, 0.8, 'F');

  // Profile card
  const cardY = 105;
  roundRect(doc, 20, cardY, pw - 40, 48, 3, CARD_BG);
  // Card border
  setD(doc, RULE);
  doc.setLineWidth(0.3);
  doc.roundedRect(20, cardY, pw - 40, 48, 3, 3, 'S');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  setC(doc, LABEL);
  doc.text('YOUR PROFILE', pw / 2, cardY + 9, { align: 'center' });

  const profile = [
    ['Age', `${inputs.age} yrs`],
    ['Sex', inputs.sex.charAt(0).toUpperCase() + inputs.sex.slice(1)],
    ['Weight', `${inputs.weightKg} kg`],
    ['Height', `${inputs.heightCm} cm`],
    ['Body Fat', `${inputs.bodyFatPercent}%`],
    ['Equipment', inputs.equipmentAccess.charAt(0).toUpperCase() + inputs.equipmentAccess.slice(1)],
  ];

  const colW = (pw - 60) / 3;
  profile.forEach((item, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = 30 + col * colW;
    const iy = cardY + 17 + row * 14;
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    setC(doc, LABEL);
    doc.text(item[0].toUpperCase(), x, iy);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    setC(doc, DARK_TEXT);
    doc.text(item[1], x, iy + 5);
  });

  // Calorie hero
  const calY = 165;
  roundRect(doc, 20, calY, pw - 40, 38, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(20, calY, pw - 40, 38, 3, 3, 'S');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  setC(doc, PRIMARY);
  doc.text('DAILY CALORIE TARGET', pw / 2, calY + 9, { align: 'center' });

  doc.setFontSize(36);
  setC(doc, DARK_TEXT);
  doc.text(`${plan.calorieTarget}`, pw / 2, calY + 26, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  setC(doc, LABEL);
  doc.text('kcal / day', pw / 2, calY + 33, { align: 'center' });

  // Macro cards
  const macY = 215;
  const macW = (pw - 50) / 3;
  const macros = [
    { label: 'PROTEIN', value: `${plan.proteinGrams}g`, pct: `${plan.proteinPercent}%`, color: PRIMARY },
    { label: 'CARBS', value: `${plan.carbGrams}g`, pct: `${plan.carbPercent}%`, color: ACCENT_BLUE },
    { label: 'FAT', value: `${plan.fatGrams}g`, pct: `${plan.fatPercent}%`, color: ACCENT_AMBER },
  ];

  macros.forEach((m, i) => {
    const x = 20 + i * (macW + 5);
    roundRect(doc, x, macY, macW, 26, 3, CARD_BG);
    setD(doc, RULE);
    doc.roundedRect(x, macY, macW, 26, 3, 3, 'S');

    // Color top accent
    setF(doc, m.color);
    doc.rect(x + 0.5, macY + 0.5, macW - 1, 2, 'F');

    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    setC(doc, LABEL);
    doc.text(m.label, x + macW / 2, macY + 9, { align: 'center' });

    doc.setFontSize(16);
    setC(doc, DARK_TEXT);
    doc.text(m.value, x + macW / 2, macY + 18, { align: 'center' });

    doc.setFontSize(7);
    setC(doc, m.color as unknown as RGB);
    doc.text(m.pct, x + macW / 2, macY + 23, { align: 'center' });
  });

  // Summary
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setC(doc, BODY_TEXT);
  const summaryLines = doc.splitTextToSize(plan.quickSummary, pw - 50);
  doc.text(summaryLines, pw / 2, 250, { align: 'center' });

  // Footer info
  doc.setFontSize(6.5);
  setC(doc, LABEL);
  doc.text(`Generated ${today}  |  Formula: Mifflin-St Jeor  |  Protein: 1.6-2.2 g/kg LBM`, pw / 2, ph - 20, { align: 'center' });
  doc.text('This plan is for informational purposes. Consult a healthcare professional before starting any program.', pw / 2, ph - 15, { align: 'center' });

  // ======================== PAGE 2: NUTRITION ========================
  doc.addPage();
  whitePage(doc);

  let y = 20;
  y = sectionTitle(doc, y, 'Nutrition Breakdown');

  const details = [
    ['Basal Metabolic Rate (BMR)', `${Math.round(plan.tdee / 1.4)} kcal`],
    ['Total Daily Energy Expenditure (TDEE)', `${plan.tdee} kcal`],
    ['Daily Calorie Target', `${plan.calorieTarget} kcal`],
    ['Lean Body Mass', `${plan.leanBodyMass} kg`],
    ['Formula Used', 'Mifflin-St Jeor'],
    ['Diet Style', inputs.dietStyle.charAt(0).toUpperCase() + inputs.dietStyle.slice(1)],
  ];

  if (plan.weeklyCalorieRange) {
    details.push(['Recomp Cycling Range', `${plan.weeklyCalorieRange.low} - ${plan.weeklyCalorieRange.high} kcal`]);
  }

  roundRect(doc, 15, y, pw - 30, details.length * 9 + 6, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, details.length * 9 + 6, 3, 3, 'S');
  y += 6;

  details.forEach(([label, value]) => {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    setC(doc, BODY_TEXT);
    doc.text(label, 22, y + 4);
    doc.setFont('helvetica', 'bold');
    setC(doc, DARK_TEXT);
    doc.text(value, pw - 22, y + 4, { align: 'right' });
    y += 9;
  });

  y += 12;

  // Macro table
  y = sectionTitle(doc, y, 'Daily Macro Targets');

  roundRect(doc, 15, y, pw - 30, 46, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, 46, 3, 3, 'S');

  // Table header
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  setC(doc, LABEL);
  const cols = [24, 72, 108, 145];
  doc.text('MACRO', cols[0], y + 7);
  doc.text('GRAMS', cols[1], y + 7);
  doc.text('CALORIES', cols[2], y + 7);
  doc.text('% OF TOTAL', cols[3], y + 7);

  line(doc, 20, y + 9, pw - 20, y + 9, RULE);

  const macroRows = [
    { name: 'Protein', g: plan.proteinGrams, cal: plan.proteinGrams * 4, pct: plan.proteinPercent, color: PRIMARY },
    { name: 'Carbohydrates', g: plan.carbGrams, cal: plan.carbGrams * 4, pct: plan.carbPercent, color: ACCENT_BLUE },
    { name: 'Fat', g: plan.fatGrams, cal: plan.fatGrams * 9, pct: plan.fatPercent, color: ACCENT_AMBER },
  ];

  let rowY = y + 16;
  macroRows.forEach(row => {
    // Color dot
    setF(doc, row.color);
    doc.circle(21, rowY - 1, 1.5, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setC(doc, DARK_TEXT);
    doc.text(row.name, cols[0], rowY);

    doc.setFont('helvetica', 'normal');
    setC(doc, BODY_TEXT);
    doc.text(`${row.g}g`, cols[1], rowY);
    doc.text(`${row.cal} kcal`, cols[2], rowY);

    setC(doc, row.color as unknown as RGB);
    doc.setFont('helvetica', 'bold');
    doc.text(`${row.pct}%`, cols[3], rowY);
    rowY += 9;
  });

  // Total
  line(doc, 20, rowY - 4, pw - 20, rowY - 4, RULE);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  setC(doc, PRIMARY);
  doc.text('TOTAL', cols[0], rowY + 1);
  setC(doc, DARK_TEXT);
  doc.text(`${plan.proteinGrams + plan.carbGrams + plan.fatGrams}g`, cols[1], rowY + 1);
  doc.text(`${plan.calorieTarget} kcal`, cols[2], rowY + 1);
  doc.text('100%', cols[3], rowY + 1);

  y = rowY + 14;

  // Per-meal
  y = pageBreak(doc, y, 45);
  y = sectionTitle(doc, y, 'Per-Meal Breakdown (4 Meals)');

  roundRect(doc, 15, y, pw - 30, 28, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, 28, 3, 3, 'S');

  const perMeal = [
    { label: 'Calories', value: `${Math.round(plan.calorieTarget / 4)} kcal` },
    { label: 'Protein', value: `${Math.round(plan.proteinGrams / 4)}g` },
    { label: 'Carbs', value: `${Math.round(plan.carbGrams / 4)}g` },
    { label: 'Fat', value: `${Math.round(plan.fatGrams / 4)}g` },
  ];

  const mealColW = (pw - 40) / 4;
  perMeal.forEach((m, i) => {
    const x = 20 + i * mealColW;
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    setC(doc, LABEL);
    doc.text(m.label.toUpperCase(), x + mealColW / 2, y + 9, { align: 'center' });
    doc.setFontSize(13);
    setC(doc, DARK_TEXT);
    doc.text(m.value, x + mealColW / 2, y + 20, { align: 'center' });
  });

  // ======================== PAGE 3+: TRAINING ========================
  doc.addPage();
  whitePage(doc);

  y = 20;
  y = sectionTitle(doc, y, '8-Week Training Plan');

  plan.trainingPlan.forEach((week) => {
    y = pageBreak(doc, y, 18);

    // Week header
    const weekLabel = `${week.weekRange}  --  ${week.phase}${week.deload ? '  (DELOAD)' : ''}`;
    if (week.deload) {
      roundRect(doc, 15, y, pw - 30, 9, 2, [255, 245, 220]);
      setD(doc, [220, 190, 120]);
    } else {
      roundRect(doc, 15, y, pw - 30, 9, 2, PRIMARY);
    }
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    setC(doc, week.deload ? DARK_TEXT : WHITE);
    doc.text(weekLabel, 20, y + 6);
    y += 13;

    week.days.forEach(day => {
      y = pageBreak(doc, y, 8 + day.exercises.length * 6);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      setC(doc, PRIMARY);
      doc.text(`${day.day}  --  ${day.focus}`, 20, y);
      y += 5;

      day.exercises.forEach(ex => {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        setC(doc, BODY_TEXT);
        doc.text(`  ${ex.name}`, 23, y);

        doc.setFont('helvetica', 'bold');
        setC(doc, DARK_TEXT);
        doc.text(`${ex.sets} x ${ex.reps}`, pw - 22, y, { align: 'right' });

        if (ex.notes) {
          doc.setFontSize(7);
          doc.setFont('helvetica', 'italic');
          setC(doc, LABEL);
          doc.text(ex.notes, 28, y + 4);
          y += 4;
        }
        y += 5;
      });
      y += 2;
    });

    line(doc, 20, y, pw - 20, y, RULE);
    y += 5;
  });

  // ======================== CARDIO & RECOVERY ========================
  y = pageBreak(doc, y, 70);
  if (y < 30) y = 20;
  y = sectionTitle(doc, y, 'Cardio Plan');

  const cardioDetails = [
    ['Type', plan.cardioPlan.type],
    ['Sessions / Week', `${plan.cardioPlan.sessionsPerWeek}x`],
    ['Duration', plan.cardioPlan.duration],
    ['Intensity', plan.cardioPlan.intensity],
  ];

  roundRect(doc, 15, y, pw - 30, cardioDetails.length * 9 + 6, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, cardioDetails.length * 9 + 6, 3, 3, 'S');
  y += 6;

  cardioDetails.forEach(([label, value]) => {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    setC(doc, BODY_TEXT);
    doc.text(label, 22, y + 4);
    doc.setFont('helvetica', 'bold');
    setC(doc, DARK_TEXT);
    doc.text(value, pw - 22, y + 4, { align: 'right' });
    y += 9;
  });

  if (plan.cardioPlan.runningPlan) {
    y += 4;
    roundRect(doc, 15, y, pw - 30, 14, 2, [255, 248, 240]);
    setD(doc, [230, 200, 160]);
    doc.roundedRect(15, y, pw - 30, 14, 2, 2, 'S');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    setC(doc, PRIMARY);
    doc.text('Running Program', 22, y + 5);
    doc.setFont('helvetica', 'normal');
    setC(doc, BODY_TEXT);
    const runLines = doc.splitTextToSize(plan.cardioPlan.runningPlan, pw - 50);
    doc.text(runLines, 22, y + 10);
    y += 18;
  }

  y += 10;

  // Recovery
  y = pageBreak(doc, y, 50);
  y = sectionTitle(doc, y, 'Daily Recovery Checklist');

  const checklistH = plan.recoveryChecklist.length * 8 + 8;
  roundRect(doc, 15, y, pw - 30, checklistH, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, checklistH, 3, 3, 'S');
  y += 7;

  plan.recoveryChecklist.forEach(item => {
    // Checkbox square
    setD(doc, PRIMARY);
    doc.setLineWidth(0.4);
    doc.rect(22, y - 2.5, 3.5, 3.5);

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    setC(doc, BODY_TEXT);
    doc.text(item, 29, y);
    y += 8;
  });

  // ======================== NOTES PAGE ========================
  y = pageBreak(doc, y + 10, 70);
  y += 5;
  y = sectionTitle(doc, y, 'Notes & Tracking');

  roundRect(doc, 15, y, pw - 30, 55, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(15, y, pw - 30, 55, 3, 3, 'S');
  for (let i = 0; i < 6; i++) {
    const lineY = y + 9 + i * 8;
    line(doc, 22, lineY, pw - 22, lineY, RULE, 0.15);
  }

  y += 65;
  y = pageBreak(doc, y, 35);

  // Branding footer
  roundRect(doc, 25, y, pw - 50, 28, 3, CARD_BG);
  setD(doc, RULE);
  doc.roundedRect(25, y, pw - 50, 28, 3, 3, 'S');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setC(doc, PRIMARY);
  doc.text('GEAR UP TO FIT', pw / 2, y + 9, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setC(doc, BODY_TEXT);
  doc.text('Your science-backed fitness companion', pw / 2, y + 15, { align: 'center' });
  setC(doc, PRIMARY);
  doc.text('gearuptofit.com', pw / 2, y + 21, { align: 'center' });

  // Page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    pageFooter(doc, i, totalPages);
  }

  const fileName = `GearUpToFit-${plan.goalLabel.replace(/\s+/g, '-')}-Plan-${inputs.weightKg}kg.pdf`;
  doc.save(fileName);
}
