import jsPDF from 'jspdf';
import { type PlanResults, type UserInputs } from '@/lib/calculations';

// Brand colors
const RED = [220, 50, 47] as const;    // primary red
const DARK = [18, 22, 28] as const;    // dark bg
const DARKER = [12, 15, 20] as const;  // darker bg
const WHITE = [242, 242, 242] as const;
const GREY = [140, 145, 155] as const;
const LIGHT_GREY = [200, 205, 210] as const;
const CARD_BG = [24, 28, 36] as const;

type RGB = readonly [number, number, number];

function setColor(doc: jsPDF, color: RGB) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function drawRoundedRect(doc: jsPDF, x: number, y: number, w: number, h: number, r: number, fill: RGB) {
  doc.setFillColor(fill[0], fill[1], fill[2]);
  doc.roundedRect(x, y, w, h, r, r, 'F');
}

function drawLine(doc: jsPDF, x1: number, y1: number, x2: number, y2: number, color: RGB, width = 0.3) {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(width);
  doc.line(x1, y1, x2, y2);
}

function addPageFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  
  // Footer line
  drawLine(doc, 15, ph - 15, pw - 15, ph - 15, [40, 44, 52]);
  
  // Footer text
  doc.setFontSize(7);
  setColor(doc, GREY);
  doc.text('Generated by GearUpToFit Body Recomp OS — gearuptofit.com', 15, ph - 10);
  doc.text(`Page ${pageNum} of ${totalPages}`, pw - 15, ph - 10, { align: 'right' });
}

function addSectionHeader(doc: jsPDF, y: number, title: string, emoji: string): number {
  const pw = doc.internal.pageSize.getWidth();
  
  // Red accent bar
  doc.setFillColor(RED[0], RED[1], RED[2]);
  doc.rect(15, y, 3, 10, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  setColor(doc, WHITE);
  doc.text(`${emoji}  ${title}`, 22, y + 7);
  
  // Subtle line under
  drawLine(doc, 15, y + 12, pw - 15, y + 12, [40, 44, 52]);
  
  return y + 18;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  const ph = doc.internal.pageSize.getHeight();
  if (y + needed > ph - 25) {
    doc.addPage();
    // Dark background on new page
    doc.setFillColor(DARK[0], DARK[1], DARK[2]);
    doc.rect(0, 0, doc.internal.pageSize.getWidth(), ph, 'F');
    return 20;
  }
  return y;
}

export function generatePlanPDF(plan: PlanResults, inputs: UserInputs) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth(); // 210
  const ph = doc.internal.pageSize.getHeight(); // 297
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ==================== PAGE 1: COVER ====================
  // Dark background
  doc.setFillColor(DARKER[0], DARKER[1], DARKER[2]);
  doc.rect(0, 0, pw, ph, 'F');

  // Top red gradient bar
  doc.setFillColor(RED[0], RED[1], RED[2]);
  doc.rect(0, 0, pw, 4, 'F');

  // Brand
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  setColor(doc, RED);
  doc.text('GEAR UP TO FIT', pw / 2, 30, { align: 'center' });

  doc.setFontSize(8);
  setColor(doc, GREY);
  doc.text('BODY RECOMP OS', pw / 2, 36, { align: 'center' });

  // Main title
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  setColor(doc, WHITE);
  doc.text('YOUR 8-WEEK', pw / 2, 70, { align: 'center' });

  doc.setFontSize(36);
  setColor(doc, RED);
  doc.text(plan.goalLabel.toUpperCase(), pw / 2, 82, { align: 'center' });

  doc.setFontSize(32);
  setColor(doc, WHITE);
  doc.text('PLAN', pw / 2, 94, { align: 'center' });

  // Decorative line
  doc.setFillColor(RED[0], RED[1], RED[2]);
  doc.rect(pw / 2 - 25, 100, 50, 1, 'F');

  // User profile card
  const cardY = 115;
  drawRoundedRect(doc, 25, cardY, pw - 50, 50, 3, CARD_BG);

  // Profile details
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  setColor(doc, GREY);
  doc.text('YOUR PROFILE', pw / 2, cardY + 10, { align: 'center' });

  const profileItems = [
    ['Age', `${inputs.age} years`],
    ['Sex', inputs.sex.charAt(0).toUpperCase() + inputs.sex.slice(1)],
    ['Weight', `${inputs.weightKg} kg`],
    ['Height', `${inputs.heightCm} cm`],
    ['Body Fat', `${inputs.bodyFatPercent}%`],
    ['Equipment', inputs.equipmentAccess.charAt(0).toUpperCase() + inputs.equipmentAccess.slice(1)],
  ];

  const colW = (pw - 70) / 3;
  profileItems.forEach((item, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = 35 + col * colW;
    const y = cardY + 18 + row * 14;

    doc.setFontSize(7);
    setColor(doc, GREY);
    doc.text(item[0].toUpperCase(), x, y);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(item[1], x, y + 5);
  });

  // Big calorie number
  const calY = 180;
  drawRoundedRect(doc, 25, calY, pw - 50, 40, 3, CARD_BG);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  setColor(doc, RED);
  doc.text('DAILY CALORIE TARGET', pw / 2, calY + 10, { align: 'center' });

  doc.setFontSize(40);
  setColor(doc, WHITE);
  doc.text(`${plan.calorieTarget}`, pw / 2, calY + 28, { align: 'center' });

  doc.setFontSize(12);
  setColor(doc, GREY);
  doc.text('kcal / day', pw / 2, calY + 35, { align: 'center' });

  // Macro boxes
  const macroY = 230;
  const macroW = (pw - 60) / 3;
  const macros = [
    { label: 'PROTEIN', value: `${plan.proteinGrams}g`, pct: `${plan.proteinPercent}%`, color: RED },
    { label: 'CARBS', value: `${plan.carbGrams}g`, pct: `${plan.carbPercent}%`, color: [59, 130, 246] as RGB },
    { label: 'FAT', value: `${plan.fatGrams}g`, pct: `${plan.fatPercent}%`, color: [234, 179, 8] as RGB },
  ];

  macros.forEach((m, i) => {
    const x = 25 + i * (macroW + 5);
    drawRoundedRect(doc, x, macroY, macroW, 28, 3, CARD_BG);

    // Color accent top
    doc.setFillColor(m.color[0], m.color[1], m.color[2]);
    doc.rect(x, macroY, macroW, 2, 'F');

    doc.setFontSize(7);
    setColor(doc, GREY);
    doc.text(m.label, x + macroW / 2, macroY + 9, { align: 'center' });

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(m.value, x + macroW / 2, macroY + 19, { align: 'center' });

    doc.setFontSize(8);
    setColor(doc, m.color as unknown as RGB);
    doc.text(m.pct, x + macroW / 2, macroY + 25, { align: 'center' });
  });

  // Quick summary
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setColor(doc, GREY);
  const summaryLines = doc.splitTextToSize(plan.quickSummary, pw - 50);
  doc.text(summaryLines, pw / 2, 268, { align: 'center' });

  // Date + disclaimer
  doc.setFontSize(7);
  setColor(doc, [80, 85, 95]);
  doc.text(`Generated ${today} • Formula: Mifflin-St Jeor • Protein: 1.6-2.2g/kg LBM`, pw / 2, ph - 20, { align: 'center' });
  doc.text('This plan is for informational purposes. Consult a healthcare professional before starting any program.', pw / 2, ph - 15, { align: 'center' });

  // ==================== PAGE 2: NUTRITION DETAILS ====================
  doc.addPage();
  doc.setFillColor(DARK[0], DARK[1], DARK[2]);
  doc.rect(0, 0, pw, ph, 'F');

  let y = 20;
  y = addSectionHeader(doc, y, 'NUTRITION BREAKDOWN', '🎯');

  // Calculation details
  const details = [
    ['Basal Metabolic Rate (BMR)', `${Math.round(plan.tdee / 1.4)} kcal`],
    ['Total Daily Energy Expenditure (TDEE)', `${plan.tdee} kcal`],
    ['Daily Calorie Target', `${plan.calorieTarget} kcal`],
    ['Lean Body Mass', `${plan.leanBodyMass} kg`],
    ['Formula Used', 'Mifflin-St Jeor'],
    ['Diet Style', inputs.dietStyle.charAt(0).toUpperCase() + inputs.dietStyle.slice(1)],
  ];

  if (plan.weeklyCalorieRange) {
    details.push(['Recomp Cycling Range', `${plan.weeklyCalorieRange.low} – ${plan.weeklyCalorieRange.high} kcal`]);
  }

  drawRoundedRect(doc, 15, y, pw - 30, details.length * 10 + 8, 3, CARD_BG);
  y += 8;

  details.forEach(([label, value]) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, GREY);
    doc.text(label, 22, y);

    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(value, pw - 22, y, { align: 'right' });
    y += 10;
  });

  y += 10;

  // Macro detail table
  y = addSectionHeader(doc, y, 'DAILY MACRO TARGETS', '🥩');

  drawRoundedRect(doc, 15, y, pw - 30, 48, 3, CARD_BG);

  // Table header
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  setColor(doc, GREY);
  const cols = [22, 70, 105, 140, pw - 22];
  doc.text('MACRO', cols[0], y + 8);
  doc.text('GRAMS', cols[1], y + 8);
  doc.text('CALORIES', cols[2], y + 8);
  doc.text('% OF TOTAL', cols[3], y + 8);

  drawLine(doc, 20, y + 11, pw - 20, y + 11, [40, 44, 52]);

  const macroRows = [
    { name: 'Protein', g: plan.proteinGrams, cal: plan.proteinGrams * 4, pct: plan.proteinPercent, color: RED },
    { name: 'Carbohydrates', g: plan.carbGrams, cal: plan.carbGrams * 4, pct: plan.carbPercent, color: [59, 130, 246] as RGB },
    { name: 'Fat', g: plan.fatGrams, cal: plan.fatGrams * 9, pct: plan.fatPercent, color: [234, 179, 8] as RGB },
  ];

  let rowY = y + 18;
  macroRows.forEach(row => {
    // Color dot
    doc.setFillColor(row.color[0], row.color[1], row.color[2]);
    doc.circle(19, rowY - 1, 1.5, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(row.name, cols[0], rowY);

    doc.setFont('helvetica', 'normal');
    doc.text(`${row.g}g`, cols[1], rowY);
    doc.text(`${row.cal} kcal`, cols[2], rowY);

    setColor(doc, row.color as unknown as RGB);
    doc.text(`${row.pct}%`, cols[3], rowY);

    rowY += 10;
  });

  // Total row
  drawLine(doc, 20, rowY - 5, pw - 20, rowY - 5, [40, 44, 52]);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  setColor(doc, RED);
  doc.text('TOTAL', cols[0], rowY);
  doc.text(`${plan.proteinGrams + plan.carbGrams + plan.fatGrams}g`, cols[1], rowY);
  doc.text(`${plan.calorieTarget} kcal`, cols[2], rowY);
  doc.text('100%', cols[3], rowY);

  y = rowY + 15;

  // Per-meal breakdown
  y = checkPageBreak(doc, y, 50);
  y = addSectionHeader(doc, y, 'PER-MEAL BREAKDOWN (4 MEALS)', '🍽️');

  drawRoundedRect(doc, 15, y, pw - 30, 30, 3, CARD_BG);
  const perMeal = [
    { label: 'Calories', value: `${Math.round(plan.calorieTarget / 4)} kcal` },
    { label: 'Protein', value: `${Math.round(plan.proteinGrams / 4)}g` },
    { label: 'Carbs', value: `${Math.round(plan.carbGrams / 4)}g` },
    { label: 'Fat', value: `${Math.round(plan.fatGrams / 4)}g` },
  ];

  const mealColW = (pw - 40) / 4;
  perMeal.forEach((m, i) => {
    const x = 20 + i * mealColW;
    doc.setFontSize(7);
    setColor(doc, GREY);
    doc.text(m.label.toUpperCase(), x + mealColW / 2, y + 10, { align: 'center' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(m.value, x + mealColW / 2, y + 22, { align: 'center' });
  });

  // ==================== PAGE 3+: TRAINING PLAN ====================
  doc.addPage();
  doc.setFillColor(DARK[0], DARK[1], DARK[2]);
  doc.rect(0, 0, pw, ph, 'F');

  y = 20;
  y = addSectionHeader(doc, y, '8-WEEK TRAINING PLAN', '🏋️');

  plan.trainingPlan.forEach((week) => {
    y = checkPageBreak(doc, y, 20);

    // Week header
    const weekLabel = `${week.weekRange} — ${week.phase}${week.deload ? ' (DELOAD)' : ''}`;
    drawRoundedRect(doc, 15, y, pw - 30, 10, 2, week.deload ? [40, 35, 15] : [RED[0], RED[1], RED[2]]);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(weekLabel, 20, y + 7);
    y += 14;

    week.days.forEach(day => {
      y = checkPageBreak(doc, y, 8 + day.exercises.length * 7);

      // Day header
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      setColor(doc, RED);
      doc.text(`${day.day} — ${day.focus}`, 20, y);
      y += 5;

      // Exercises
      day.exercises.forEach(ex => {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        setColor(doc, LIGHT_GREY);
        doc.text(`• ${ex.name}`, 25, y);

        doc.setFont('helvetica', 'bold');
        setColor(doc, GREY);
        doc.text(`${ex.sets}×${ex.reps}`, pw - 22, y, { align: 'right' });

        if (ex.notes) {
          doc.setFontSize(7);
          doc.setFont('helvetica', 'italic');
          setColor(doc, [100, 105, 115]);
          doc.text(ex.notes, 30, y + 4);
          y += 4;
        }
        y += 5;
      });

      y += 3;
    });

    // Divider between weeks
    drawLine(doc, 20, y, pw - 20, y, [35, 38, 45]);
    y += 5;
  });

  // ==================== CARDIO & RECOVERY PAGE ====================
  y = checkPageBreak(doc, y, 80);
  if (y < 30) y = 20;
  y = addSectionHeader(doc, y, 'CARDIO PLAN', '🏃');

  const cardioDetails = [
    ['Type', plan.cardioPlan.type],
    ['Sessions/Week', `${plan.cardioPlan.sessionsPerWeek}×`],
    ['Duration', plan.cardioPlan.duration],
    ['Intensity', plan.cardioPlan.intensity],
  ];

  drawRoundedRect(doc, 15, y, pw - 30, cardioDetails.length * 10 + 8, 3, CARD_BG);
  y += 8;
  cardioDetails.forEach(([label, value]) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, GREY);
    doc.text(label, 22, y);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(value, pw - 22, y, { align: 'right' });
    y += 10;
  });

  if (plan.cardioPlan.runningPlan) {
    y += 3;
    drawRoundedRect(doc, 15, y, pw - 30, 15, 2, [30, 25, 20]);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    setColor(doc, RED);
    doc.text('🏃 Running Program', 22, y + 6);
    doc.setFont('helvetica', 'normal');
    setColor(doc, LIGHT_GREY);
    const runLines = doc.splitTextToSize(plan.cardioPlan.runningPlan, pw - 50);
    doc.text(runLines, 22, y + 11);
    y += 18;
  }

  y += 10;

  // Recovery checklist
  y = checkPageBreak(doc, y, 60);
  y = addSectionHeader(doc, y, 'DAILY RECOVERY CHECKLIST', '💚');

  drawRoundedRect(doc, 15, y, pw - 30, plan.recoveryChecklist.length * 9 + 8, 3, CARD_BG);
  y += 8;
  plan.recoveryChecklist.forEach(item => {
    // Checkbox
    doc.setDrawColor(RED[0], RED[1], RED[2]);
    doc.setLineWidth(0.4);
    doc.rect(22, y - 3, 4, 4);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, LIGHT_GREY);
    doc.text(item, 30, y);
    y += 9;
  });

  // ==================== FINAL PAGE: NOTES + BRANDING ====================
  y = checkPageBreak(doc, y, 80);
  y += 10;
  y = addSectionHeader(doc, y, 'NOTES & TRACKING', '📝');

  // Empty lined note area
  drawRoundedRect(doc, 15, y, pw - 30, 60, 3, CARD_BG);
  for (let i = 0; i < 6; i++) {
    const lineY = y + 10 + i * 9;
    drawLine(doc, 22, lineY, pw - 22, lineY, [35, 38, 45], 0.2);
  }

  y += 70;
  y = checkPageBreak(doc, y, 40);

  // Branding footer
  drawRoundedRect(doc, 25, y, pw - 50, 30, 3, CARD_BG);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setColor(doc, RED);
  doc.text('GEAR UP TO FIT', pw / 2, y + 10, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setColor(doc, GREY);
  doc.text('Your science-backed fitness companion', pw / 2, y + 16, { align: 'center' });
  doc.text('gearuptofit.com', pw / 2, y + 22, { align: 'center' });

  // Add page numbers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageFooter(doc, i, totalPages);
  }

  // Download
  const fileName = `GearUpToFit-${plan.goalLabel.replace(/\s+/g, '-')}-Plan-${inputs.weightKg}kg.pdf`;
  doc.save(fileName);
}
